# Test goal: build with HIP to check HIP compilation
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: gcc-9
#   GPU: HIP
#   Scope: configure, build
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: RelWithAssert
#   Compiler: gcc-9
#   MPI: threadMPI (AMD build)
#   SIMD: AVX2_256

gromacs:gcc-9-hip-602:configure:
  extends:
    - .gromacs:base:configure
    - .use-gcc:base
    - .use-hip
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-9-rocm-6.0.2
  variables:
    CMAKE: /usr/local/cmake-3.24.0/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX2_256"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    COMPILER_MAJOR_VERSION: 9

gromacs:gcc-9-hip-602:build:
  extends:
    - .gromacs:base:build
    - .use-gcc:base
    - .use-ccache
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-9-rocm-6.0.2
  variables:
    CMAKE: /usr/local/cmake-3.24.0/bin/cmake
  needs:
    - job: gromacs:gcc-9-hip-602:configure

# TODO enable tests once there is something to test
#gromacs:gcc-9-hip-602:test:
#  extends:
#    - .gromacs:base:test
#  rules:
#    - !reference [.rules:skip-if-single-amd-gpu-unavailable, rules]    
#    - !reference [.rules:post-merge-acceptance, rules]                 
#  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-9-rocm-6.0.2
#  variables:
#    CMAKE: /usr/local/cmake-3.24.0/bin/cmake
#    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
#    GPU_VENDOR: "AMD"
#    GPU_COUNT: 1         
#  tags:
#    - $GITLAB_RUNNER_TAG_1X_AMD_GPU
#  needs:
#    - job: gromacs:gcc-9-hip-602:build
#
#gromacs:gcc-9-hip-602:regressiontest:
#  extends:
#    - .gromacs:base:regressiontest
#  rules:
#    - !reference [.rules:skip-if-single-amd-gpu-unavailable, rules]        
#    - !reference [.rules:post-merge-acceptance, rules]                     
#  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-9-rocm-6.0.2
#  variables:
#    CMAKE: /usr/local/cmake-3.24.0/bin/cmake
#    REGRESSIONTEST_TOTAL_RANK_NUMBER: 1
#    REGRESSIONTEST_OMP_RANK_NUMBER: 2
#  tags:
#    - $GITLAB_RUNNER_TAG_1X_AMD_GPU
#  needs:
#    - job: gromacs:gcc-9-hip-602:build
#    - job: regressiontests:prepare
